#object/rendering Configuration
target_resolution: 512
background_color: 1.0

#Neural Gaffer Configuration
neural_gaffer:
  base_model_id: "kxic/zero123-xl" #this is the base model that they used
  checkpoint_dir: "./neural_gaffer_res256/checkpoint-80000"

#environment map generator configuration
env_map:
  metadata_path: "./env_map/envmapsmetadata.json"
  exr_folder: "./env_map/"
  light_source_threshold: 20.0
  enable_custom_generation: true  #set to false if you dont want custom envmap generation

#Real-ESRGAN upsampler configuration
upsampler:
  use_tiling: false  #for low VRAM devices, this can be set to true, to reduce VRAM consumption
